### ISSUE TITLE
ML프로젝트 협업 방법 조사

### ISSUE THREAD

**Issue by livlikwav** [GangnamDevelopers/naengboo-status#6]
# What

- 백엔드나 앱이 아닌, ML프로젝트의 협업을 어떤식으로 진행하는지 조사

# Why

- 팀 구성원들 간의 업무 진행 상황은 투명하게 공유되어야 한다.
- ML팀의 업무 진행 상황과 실제 코드를 모든 팀원이 확인할 수 있어야 한다.

# Description

ML프로젝트는 github를 별도로 사용하지 않는 것 같던데,
그렇다면 어떤식으로 팀원 간에 협업 및 소통을 진행하는지 조사 및 적용이 필요하다.

**Comment by hoyeon94** [comment]
- 혹시 경민님의 회사에서는 어떤 방식으로 코드를 관리하나요? 제가 인턴하는 곳은 그냥 인공지능 전용으로 깃 파서 코드 공유하는 식입니다,,

**Comment by livlikwav** [comment]
저는 ML팀이 아니기도 하고, 그동안 해본적이 없어서 모르겠네요.
궁금한 점은, 
예를 들어서 촬영한 냉장고 사진을 입력하면 냉장고 안 재료들을 인식해서 그 리스트를 출력해주는 모델을 학습한다고 하면,

(저도 ml 잘 몰라서 정확하진 않지만)
- 해당 모델의 데이터 셋
- 학습 진행 상황
- 학습을 위한 코드
- ...
등과 같이 계속 변화하는 부분이 있고 할텐데
이런것들을 다 깃허브로 저장하는지?

그리고 학습이 끝난 모델은 어떤 식으로 저장하는지
버저닝은 어떻게 하는지
실제 서비스 적용을 하면 어떻게 데이터를 모으고, 적용하여 개선시키는지 등이 궁금합니다

**Comment by hoyeon94** [comment]
아하,, 일단

- 데이터 셋
회사에서는 pachyderm이라는 데이터 레포에다가 minio라는 저장소 연결해서 사용하는데, 사실 큰 프로젝트가 아닌 이상 이렇게 구성하게 되면 배보다 배꼽이 더 커지지 않을까 생각합니당,, 그냥 구글드라이브 파서 데이터 공유해도 크게 문제 없을 것 같아요
- 학습 코드
이거는 그냥 깃 파서 코드를 공유하면 될 것 같네요, 인공지능을 위한 코드만 따로 그룹지어서 관리하면 될 것 같아요
- 학습 진행 상황 및 학습이 끝난 모델 저장
mlflow라는거를 이용할 생각입니다. mlflow에다가 학습 중 발생한 로그랑 학습결과 모델파일을 저장할 수 있어요, 나중에 사용법같은거는 위키에 한번 올리도록 하겠습니다. 학습마다 모델을 따로 저장할 수 있기 때문에, 버저닝도 mlflow에서 할 수 있기는 합니다.
- 배포
배포는 onnx라는 프레임워크를 배워서 써보려고 했는데, 난이도가 어떤지 잘 몰라서 확실하게 말씀드리긴 어렵네요. onnx를 못 쓰게 된다면 그냥 flask기반으로 인공지능 전용 서버 파서 배포해도 될 것 같아요.

일단 제가 아는거로만 말해봤는데, 다른 의견 있다면 말씀해주시면 감사하겠습니다~

**Comment by livlikwav** [comment]
중요한 키워드를 많이 짚어주셔서 찾아보면서 감을 잡는데 도움이 되었네요.

나름 찾아본거 정리하자면
- pachyderm
  - 데이터를 위한 version control system 같은 것 
  - 잘 이해하지 못했지만... 데이터 과학 실험을 위한 Pipeline을 구성하고, 배포하는데에도 도움을 줌
- minio
  - 오픈소스 object storage
  - AWS S3와 호환됨, 사실상 업계 표준
- mlflow
  - 머신러닝 학습을 위한 플랫폼?
  - 학습현황 시각화, plot 등? (다 살펴보지 않음)
- onnx ( 안 찾아봄 ) ㅎㅎ..

이 정도로 생각해두신게 있다면 충분한 거 같습니다.
상세한 설계는 repo 파고 진행하시면 될 것 같습니다.
